### PR TITLE
mavis: specify SONAME for libmavis.so

### PR DESCRIPTION
**Pull request by jirutka**
This fixes the problem that the tac_plus-ng binary is linked against libmavis.so (without version), instead of libmavis.so.0.

### CODE REVIEW

**Comment by MarcJHuber** [comment]
Hi Jakub,

thanks ... could you please go into detail why linking to a .so could pose a problem? Currently, there's no library versioning support at all, mostly because the various compile-time options make that virtually impossible. Concurrent installations may reside in the same file system, but not in the same hierarchy.

Cheers,

Marc

**Comment by MarcJHuber** [comment]
No response implies no merge.

**Comment by jirutka** [comment]
I’m sorry for the late response.

> could you please go into detail why linking to a .so could pose a problem?

Because the library is installed as `libmavis.so.0.1` (with symlinks `libmavis.so.0` and `libmavis.so`) – the library name with the version suffix is supposed to reflect `SONAME`. That’s the de facto standard and build systems (in Linux distros) rely on it.

> Currently, there's no library versioning support at all

So what’s `LIBVER_MAJOR` and `LIBVER_MINOR` in [mavis/Makefile.obj:22](https://github.com/MarcJHuber/event-driven-servers/blob/a185d902480c99360a357461f65bfbf7b9d27a1d/mavis/Makefile.obj#L22-L23)?

> …mostly because the various compile-time options make that virtually impossible.

Is this library actually intended to be used by other programs, or just by tacacs+ng?

**Comment by MarcJHuber** [comment]
Hi Jakub,

the library is used by ftpd, tac_plus, tac_plus-ng, the dynamically loaded MAVIS modules plus most of the other optional parts (radmavis, radldap, radldap-mt, ...). It doesn't provide a stable public API and is tailor-made to meet the requirement of the other parts in that GIT.

But yes, if only tac_plus-ng is of interest (and, to be honest, I only keep tac_plus, ftpd and tcprelay there for legacy reasons) then the library is used solely by tac_plus-ng.

I understand that in order to separate packages for the various components of the GIT (ftpd, ...) could perhaps require versioning, On the other hand, I didn't implement versioning for the MAVIS modules (libmavis_external.so, for example) either, It is simply not intended that different versions be installed on the same system, and whenever that core library is updated all binaries using that need to follow.

Cheers,

Marc

**Pull request closed without merging**
